application: unc-desi
version: 1
runtime: python27
threadsafe: false
api_version: 1

handlers:
- url: /
  script: assets/index.py

- url: /.*\.html
  script: assets/index.py

- url: /assets/js
  mime_type: application/javascript
  static_dir: assets/js

- url: /assets/css
  mime_type: text/css
  static_dir: assets/css

- url: /assets/images
  static_dir: assets/images

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
